"""Migration plan generator - creates actionable migration roadmaps."""

import os
from datetime import datetime

from opsmind.schemas.assessment import AssessmentResult


class MigrationPlanGenerator:
    """Generates step-by-step migration plans with risk assessment."""

    def __init__(self, output_dir: str) -> None:
        self.output_dir = output_dir

    def generate(self, assessment_results: dict[str, AssessmentResult]) -> list[str]:
        """Generate migration plans for each host.

        Args:
            assessment_results: Assessment results per host

        Returns:
            List of generated file paths
        """
        generated: list[str] = []

        for hostname, result in assessment_results.items():
            plan = self._generate_plan(hostname, result)

            plan_dir = os.path.join(self.output_dir, "plans")
            os.makedirs(plan_dir, exist_ok=True)

            plan_path = os.path.join(plan_dir, f"{hostname}_migration_plan.md")
            with open(plan_path, "w") as f:
                f.write(plan)
            generated.append(plan_path)

        # Generate summary plan
        summary = self._generate_summary_plan(assessment_results)
        summary_path = os.path.join(self.output_dir, "plans", "00_migration_overview.md")
        with open(summary_path, "w") as f:
            f.write(summary)
        generated.append(summary_path)

        return generated

    def _generate_plan(self, hostname: str, result: AssessmentResult) -> str:
        """Generate migration plan for a single host."""
        feas = result.feasibility
        comp = result.complexity
        sizing = result.resource_sizing

        phases_text = ""
        for i, phase in enumerate(result.migration_strategy.phases, 1):
            phases_text += (
                f"### Phase {i}: {phase.get('name', '')}\n\n"
                f"**Duration**: {phase.get('duration', 'TBD')}\n\n"
                f"**Tasks**:\n"
                f"- [ ] Prepare environment\n"
                f"- [ ] Configure dependencies\n"
                f"- [ ] Execute migration\n"
                f"- [ ] Verify functionality\n\n"
            )

        recs = "\n".join(f"- [ ] {r}" for r in feas.recommendations)

        skills = "\n".join(f"- {s}" for s in comp.skill_requirements)

        return f"""# Migration Plan: {hostname}

**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Strategy**: {result.migration_strategy.strategy_type}
**Estimated Effort**: {comp.estimated_effort_days} days
**Complexity**: {feas.complexity.value.upper()}
**Risk Level**: {feas.risk_level.value.upper()}

---

## Pre-Migration Checklist

{recs}

---

## Migration Phases

{phases_text}

## Rollback Plan

{result.migration_strategy.rollback_strategy}

## Resource Requirements

- CPU: {sizing.cpu_cores} cores
- Memory: {sizing.memory_gb} GB
- Storage: {sizing.storage_gb} GB

## Required Skills

{skills}

## Risks

{chr(10).join(f"- {r}" for r in result.migration_strategy.risks)}

---

*Generated by OpsMind v0.1.0 | Review and customize before execution*
"""

    def _generate_summary_plan(self, results: dict[str, AssessmentResult]) -> str:
        """Generate overall migration overview."""
        total_effort = sum(r.complexity.estimated_effort_days or 0 for r in results.values())
        avg_score = sum(r.feasibility.overall_score for r in results.values()) / max(len(results), 1)

        host_summaries = ""
        for hostname, result in results.items():
            host_summaries += (
                f"| {hostname} | {result.feasibility.overall_score:.0f} | "
                f"{result.feasibility.complexity.value} | "
                f"{result.migration_strategy.strategy_type} | "
                f"{result.complexity.estimated_effort_days or 'TBD'} |\n"
            )

        timeline = ""
        current_phase = 0
        for hostname, result in results.items():
            fe = result.complexity.estimated_effort_days or 5
            timeline += f"| {hostname} | Phase {current_phase + 1} | Day {current_phase + 1}-{current_phase + fe} |\n"
            current_phase += fe

        return f"""# Migration Overview

**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Total Hosts**: {len(results)}
**Average Score**: {avg_score:.1f}/100
**Total Estimated Effort**: {total_effort} days

---

## Host Summary

| Host | Score | Complexity | Strategy | Effort |
|------|-------|------------|----------|--------|
{host_summaries}

## Suggested Timeline

| Host | Phase | Duration |
|------|-------|----------|
{timeline}

## Key Risks

- Data consistency during migration
- Application downtime window
- Configuration drift
- Dependent service availability

## Success Criteria

- [ ] All applications running in containers
- [ ] Data integrity verified
- [ ] Performance meets or exceeds baseline
- [ ] Monitoring and alerting configured
- [ ] Rollback plan documented and tested

---

*Generated by OpsMind v0.1.0 | This is an AI-assisted plan - review by operations team required*
"""
